name: "BigFile Tests"
on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Build bigfile test sources
        run: |
          rm -rf _build || true
          ./big-rebar3 test compile
          chmod -R u+w ./_build
          tar --dereference -czf /tmp/bigfile_build_${{ github.run_id }}.tar.gz _build

  eunit-tests:
    needs: build
    runs-on: self-hosted
    strategy:
      fail-fast: true
      max-parallel: 12
      matrix:
        core_test_mod: [
            ## Long-running tests. Put these first to limit the overall runtime of the 
            ## test suite
            big_coordinated_mining_tests,
            big_data_sync_tests,
            big_fork_recovery_tests,
            big_multiple_txs_per_wallet_tests,
            big_packing_tests,
            big_poa,
            big_vdf_server_tests,
            big_post_block_tests,
            big_reject_chunks_tests,

            ## Modules containing tests
            big,
            big_block,
            big_block_cache,
            big_chain_stats,
            big_chunk_storage,
            big_data_sync_worker_master,
            big_deep_hash,
            big_diff_dag,
            big_ets_intervals,
            big_events,
            big_inflation,
            big_intervals,
            big_join,
            big_kv,
            big_merkle,
            big_mining_server,
            big_mining_stats,
            big_node,
            big_node_utils,
            big_nonce_limiter,
            # big_p3,
            # big_p3_config,
            # big_p3_db,
            big_packing_server,
            big_patricia_tree,
            big_peers,
            big_pricing,
            big_retarget,
            big_serialize,
            big_storage_module,
            big_storage,
            big_sync_buckets,
            big_sync_record,
            big_tx,
            big_tx_db,
            big_unbalanced_merkle,
            big_util,
            big_verify_chunks,
            big_wallet,
            big_webhook,
            big_pool,

            ## Test modules (note: that _tests are implicitly run by a matching prefix name
            big_base64_compatibility_tests,
            big_config_tests,
            big_difficulty_tests,
            big_header_sync_tests,
            big_http_iface_tests,
            big_http_util_tests,
            big_info_tests,
            big_mempool_tests,
            big_mine_randomx_tests,
            big_mine_vdf_tests,
            big_mining_io_tests,
            big_poller_tests,
            big_reject_chunks_tests,
            big_semaphore_tests,
            big_start_from_block_tests,
            big_tx_blacklist_tests,
            big_tx_replay_pool_tests,
            big_vdf_tests,
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Extract build artifact
        run: |
          if [ ! -d "_build_${{ github.run_id }}" ]; then
            rm -rf _build || true
            tar -xzf /tmp/bigfile_build_${{ github.run_id }}.tar.gz
            mv ./_build ./_build_${{ github.run_id }}
          fi
      - name: Restart epmd
        run: |
          if ! pgrep -x "epmd" > /dev/null
          then
            echo "Starting epmd"
            epmd -relaxed_command_check -daemon
          fi
      - name: ${{ matrix.core_test_mod }}.erl
        id: tests
        run: |
          rm -f *.out || true
          EXIT_CODE=0
          export PATH=$(pwd)/_build_${{ github.run_id }}/erts/bin:$PATH
          export ERL_EPMD_ADDRESS=127.0.0.1
          export TIMESTAMP_IN_MILLISECONDS=$(date +%s%3N)
          export NAMESPACE="${{ matrix.core_test_mod }}_${TIMESTAMP_IN_MILLISECONDS}"
          export ERL_TEST_OPTS="-pa $(echo $(pwd)/_build_${{ github.run_id }}/test/lib/*/ebin) $(pwd)/_build_${{ github.run_id }}/test/lib/bigfile/test -config $(pwd)/config/sys.config"
          RETRYABLE=1
          while [[ $RETRYABLE -eq 1 ]]; do
            RETRYABLE=0
            set +e
            set -x
            erl +S 4:4 $ERL_TEST_OPTS -noshell -name main-${NAMESPACE}@127.0.0.1 -setcookie ${{ matrix.core_test_mod }} -run ar tests "${{ matrix.core_test_mod }}" -s init stop 2>&1 | tee main.out
            EXIT_CODE=${PIPESTATUS[0]}
            set +x
            set -e
            # For debugging purposes, print the peer1 output if the tests failed
            if [[ $EXIT_CODE -ne 0 ]]; then
              echo -e "\033[0;32m===> Checking for retry\033[0m"
              if ls peer1-*.out 1> /dev/null 2>&1; then
                first_line_peer1=$(head -n 1 peer1-*.out)
              fi
              first_line_main=$(head -n 1 main.out)
              echo -e "\033[0;31m===> First line of peer1 node's output: $first_line_peer1\033[0m"
              echo -e "\033[0;31m===> First line of main node's output: $first_line_main\033[0m"

              # Check if it is a retryable error
              if [[ "$first_line_peer1" == "Protocol 'inet_tcp': register/listen error: "* ]]; then
                echo "Retrying test because of inet_tcp error..."
                RETRYABLE=1
                sleep 1
              elif [[ "$first_line_peer1" == "Protocol 'inet_tcp': the name"* ]]; then
                echo "Retrying test because of inet_tcp clash..."
                RETRYABLE=1
                sleep 1
              elif [[ "$first_line_main" == *"econnrefused"* ]]; then
                echo "Retrying test because of econnrefused..."
                RETRYABLE=1
                sleep 1
              else
                if ls peer1-*.out 1> /dev/null 2>&1; then
                  echo -e "\033[0;31m===> Test failed, printing the peer1 node's output...\033[0m"
                  cat peer1-*.out
                else
                  echo -e "\033[0;31m===> Test failed without peer1 output...\033[0m"
                fi
                if ls peer2-*.out 1> /dev/null 2>&1; then
                  echo -e "\033[0;31m===> Test failed, printing the peer2 node's output...\033[0m"
                  cat peer2-*.out
                else
                  echo -e "\033[0;31m===> Test failed without peer2 output...\033[0m"
                fi
                if ls peer3-*.out 1> /dev/null 2>&1; then
                  echo -e "\033[0;31m===> Test failed, printing the peer3 node's output...\033[0m"
                  cat peer3-*.out
                else
                  echo -e "\033[0;31m===> Test failed without peer3 output...\033[0m"
                fi
                if ls peer4-*.out 1> /dev/null 2>&1; then
                  echo -e "\033[0;31m===> Test failed, printing the peer4 node's output...\033[0m"
                  cat peer4-*.out
                else
                  echo -e "\033[0;31m===> Test failed without peer4 output...\033[0m"
                fi
              fi
            fi
          done
          echo "exit_code=$EXIT_CODE" >> $GITHUB_ENV # Set the exit_code output variable using Environment Files
          exit $EXIT_CODE # exit with the exit code of the tests
      - name: Cleanup successful test
        if: steps.tests.outputs.exit_code == '0' # Conditional based on the output variable
        run: rm -rf logs *.out .tmp

  cleanup:
    needs: eunit-tests
    runs-on: self-hosted
    if: ${{ success() && needs.eunit-tests.result == 'success' }}
    steps:
      - name: Cleanup build directories
        run: |
          rm -rf /tmp/bigfile_build_${{ github.run_id }}.tar.gz
          find /home/runner -type d -name "_build_${{ github.run_id }}" -exec rm -rf {} +
      - name: Cleanup old build artifacts
        run: |
          find /tmp -maxdepth 1 -name "bigfile_build_*" -type f -mtime +7 -exec rm -f {} +
          find /home/runner -name "_build_*" -type d -mtime +7 -exec rm -rf {} +
